#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TabbedApplication.Resource", IsApplication=true)]

namespace TabbedApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050003
			public const int CC_arrays = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int GVW_array = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int NCB_arrays = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int YesORNo = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int age_array = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int vachicle_arrays = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int vachicle_value_arrays = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int MyButton = 2131099649;
			
			// aapt resource value: 0x7f060026
			public const int ScrollLayout1 = 2131099686;
			
			// aapt resource value: 0x7f060002
			public const int ScrollView1 = 2131099650;
			
			// aapt resource value: 0x7f060044
			public const int btn_Calculate = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int btn_DetailsBreakUp = 2131099717;
			
			// aapt resource value: 0x7f06002b
			public const int ddl_AgeOfVechicle = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int ddl_CC = 2131099693;
			
			// aapt resource value: 0x7f060030
			public const int ddl_GVW = 2131099696;
			
			// aapt resource value: 0x7f060043
			public const int ddl_InclusionOfIMT23 = 2131099715;
			
			// aapt resource value: 0x7f06002f
			public const int ddl_NCB = 2131099695;
			
			// aapt resource value: 0x7f060037
			public const int ddl_PAToOwnerDriver = 2131099703;
			
			// aapt resource value: 0x7f060029
			public const int ddl_TypeOfVechicle = 2131099689;
			
			// aapt resource value: 0x7f060007
			public const int et_AddTon = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int et_Discount = 2131099657;
			
			// aapt resource value: 0x7f060033
			public const int et_IDV = 2131099699;
			
			// aapt resource value: 0x7f06000d
			public const int et_IMT23PaintChrgs = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int et_LLToPassengers = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int et_LLtoDrAndCl = 2131099669;
			
			// aapt resource value: 0x7f06003d
			public const int et_LgLabtoNumberofDriversandCleaners = 2131099709;
			
			// aapt resource value: 0x7f06000b
			public const int et_NCB = 2131099659;
			
			// aapt resource value: 0x7f060036
			public const int et_NoOfPassBusOrTaxi = 2131099702;
			
			// aapt resource value: 0x7f060005
			public const int et_ODBasic = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int et_ODTotal = 2131099663;
			
			// aapt resource value: 0x7f06003b
			public const int et_PASumInsuredforDriverandCleaner = 2131099707;
			
			// aapt resource value: 0x7f060041
			public const int et_PASumInsuredforUnnamed = 2131099713;
			
			// aapt resource value: 0x7f06001b
			public const int et_PAToDrAndCleaner = 2131099675;
			
			// aapt resource value: 0x7f060039
			public const int et_PAToDriverCleaner = 2131099705;
			
			// aapt resource value: 0x7f060019
			public const int et_PAToNonFarePass = 2131099673;
			
			// aapt resource value: 0x7f060013
			public const int et_PAToOwnerDriver = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int et_PAToUnnamedPassengers = 2131099677;
			
			// aapt resource value: 0x7f06003f
			public const int et_PAtoUnnamedPassengersforPrivateCar = 2131099711;
			
			// aapt resource value: 0x7f060023
			public const int et_ServiceTax = 2131099683;
			
			// aapt resource value: 0x7f060011
			public const int et_TPBasic = 2131099665;
			
			// aapt resource value: 0x7f06001f
			public const int et_TPTotal = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int et_TotalPrem = 2131099681;
			
			// aapt resource value: 0x7f060025
			public const int et_TotolAmount = 2131099685;
			
			// aapt resource value: 0x7f060000
			public const int fragmentContainer = 2131099648;
			
			// aapt resource value: 0x7f060027
			public const int tableLayout1 = 2131099687;
			
			// aapt resource value: 0x7f060003
			public const int tableLayout11 = 2131099651;
			
			// aapt resource value: 0x7f060028
			public const int tableRow1 = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int tableRow2 = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int tableRow3 = 2131099692;
			
			// aapt resource value: 0x7f060031
			public const int tableRow4 = 2131099697;
			
			// aapt resource value: 0x7f06002e
			public const int tableRow5 = 2131099694;
			
			// aapt resource value: 0x7f060034
			public const int tableRow6 = 2131099700;
			
			// aapt resource value: 0x7f060006
			public const int tv_AddTon = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int tv_Discount = 2131099656;
			
			// aapt resource value: 0x7f060032
			public const int tv_IDV = 2131099698;
			
			// aapt resource value: 0x7f06000c
			public const int tv_IMT23PaintChrgs = 2131099660;
			
			// aapt resource value: 0x7f060042
			public const int tv_InclusionOfIMT23 = 2131099714;
			
			// aapt resource value: 0x7f060016
			public const int tv_LLToPassengers = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int tv_LLtoDrAndCl = 2131099668;
			
			// aapt resource value: 0x7f06003c
			public const int tv_LgLabtoNumberofDriversandCleaners = 2131099708;
			
			// aapt resource value: 0x7f06000a
			public const int tv_NCB = 2131099658;
			
			// aapt resource value: 0x7f060035
			public const int tv_NoOfPassBusOrTaxi = 2131099701;
			
			// aapt resource value: 0x7f060004
			public const int tv_ODBasic = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int tv_ODTotal = 2131099662;
			
			// aapt resource value: 0x7f06003a
			public const int tv_PASumInsuredforDriverandCleaner = 2131099706;
			
			// aapt resource value: 0x7f060040
			public const int tv_PASumInsuredforUnnamed = 2131099712;
			
			// aapt resource value: 0x7f06001a
			public const int tv_PAToDrAndCleaner = 2131099674;
			
			// aapt resource value: 0x7f060038
			public const int tv_PAToDriverCleaner = 2131099704;
			
			// aapt resource value: 0x7f060018
			public const int tv_PAToNonFarePass = 2131099672;
			
			// aapt resource value: 0x7f060012
			public const int tv_PAToOwnerDriver = 2131099666;
			
			// aapt resource value: 0x7f06001c
			public const int tv_PAToUnnamedPassengers = 2131099676;
			
			// aapt resource value: 0x7f06003e
			public const int tv_PAtoUnnamedPassengersforPrivateCar = 2131099710;
			
			// aapt resource value: 0x7f060022
			public const int tv_ServiceTax = 2131099682;
			
			// aapt resource value: 0x7f060010
			public const int tv_TPBasic = 2131099664;
			
			// aapt resource value: 0x7f06001e
			public const int tv_TPTotal = 2131099678;
			
			// aapt resource value: 0x7f060046
			public const int tv_TotalAmount = 2131099718;
			
			// aapt resource value: 0x7f060020
			public const int tv_TotalPrem = 2131099680;
			
			// aapt resource value: 0x7f060024
			public const int tv_TotolAmount = 2131099684;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Tab1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Tab2 = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int CalculationActivity = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int DetailsBreakUpActivity = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int vachicle_prompt = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
